'''
Corrections for the XPAR PDFs.
'''

import sqlite3 as lite


def Corrections(tbl):

    # connections
    con = lite.connect('XPAR_PDF.db')
    cur = con.cursor()
    
    # correct comments for 0% interest notifications
    cur.execute("update {} set COMMENT='XPAR_PDF' where INTEREST=0.0;".format(tbl))

    # delete incorrect ISINs
    cur.execute("delete from {} where LENGTH(ISIN) <> 12;".format(tbl))
    cur.execute("delete from {} where ISIN like '% %';".format(tbl))
    con.commit()

    # set HOLDERs correct
    holders = { "FREDERICK INVESTMENT": "FREDERICK INVESTMENTS, LTD.",
    "GAVAUDAN": "BOUSSARD & GAVAUDAN ASSET MANAGEMENT LP",
    "CANADA PENSION PLAN": "CANADA PENSION PLAN INVESTMENT BOARD",
    "KAIROS PARTNERS" : "KAIROS PARTNERS SGR S.P.A.",
    "KAIROS INVESTMENT" : "KAIROS INVESTMENT MANAGEMENT LIMITED",
    "CADIAN CAPITAL" : "CADIAN CAPITAL MANAGEMENT, LLC",
    "SYQUANT CAPITAL" : "SYQUANT CAPITAL",
    "AHL PARTNERS" : "AHL PARTNERS LLP",
    "ANCHORAGE CAPITAL MASTER" : "ANCHORAGE CAPITAL MASTER OFFSHORE, LTD",
    "AQR CAPITAL MANAGEMENT" : "AQR CAPITAL MANAGEMENT, LLC",
    "ARROWGRASS CAPITAL PARTNERS": "ARROWGRASS CAPITAL PARTNERS L.L.P.",  
    "G MASTER FUND" : "B&G MASTER FUND PLC",
    "BALYASNY ASSET MANAGEMENT" : "BALYASNY ASSET MANAGEMENT, L.P.",
    "BLACKROCK INVESTMENT MANAGEMENT" : "BLACKROCK INVESTMENT MANAGEMENT UK LIMITED",
    "BLACKROCK INSTITUTIONAL TRUST" : "BLACKROCK INSTITUTIONAL TRUST COMPANY NATIONAL ASSOCIATION", 
    "BLACKROCK INVESTMENT MANAGEMENTUK" :"BLACKROCK INVESTMENT MANAGEMENT UK LIMITED",           
    "BLACKWELL PARTNERS" : "BLACKWELL PARTNERS, LLC",
    "BNP PARIBAS" : "BNP PARIBAS SA",
    "BOSTON PARTNERS GLOBAL" : "BOSTON PARTNERS GLOBAL INVESTORS INC",
    "CAPITAL FUND MANAGEMENT": "CAPITAL FUND MANAGEMENT SA",
    "CARLSON CAPITAL UK" : "CARLSON CAPITAL UK LLP",
    "CITADEL ADVISORS II LLC": "CITADEL ADVISORS II LLC",
    "CITADEL ADVISORS LLC" : "CITADEL ADVISORS LLC",
    "CITADEL EUROPE LLP" : "CITADEL EUROPE LLP",
    "COLTRANE MASTER FUND": "COLTRANE MASTER FUND, L.P.",
    "CONNOR, CLARK & LUNN INVESTMENTM": "CONNOR, CLARK & LUNN INVESTMENT MANAGEMENT LTD",
    "CQS UK": "CQS UK LLP",
    "D.E. SHAW": "D.E. SHAW & CO. L.P.",
    "DAVIDSON KEMPNER EUROPEAN" : "DAVIDSON KEMPNER EUROPEAN PARTNERS, LLP",
    "DISCOVERY CAPITAL MANAGEMENT" : "DISCOVERY CAPITAL MANAGEMENT, LLC",
    "DSAM PARTNERS": "DSAM PARTNERS LLP",
    "ETON PARK INTERNATIONAL LLP" : "ETON PARK INTERNATIONAL LLP",
    "EVERPOINT ASSET MANAGEMENT, LLC" : "EVERPOINT ASSET MANAGEMENT, LLC",
    "EXANE ASSET MANAGEMENT" : "EXANE ASSET MANAGEMENT",
    "FIR TREE" : "FIR TREE INC.",
    "GSA CAPITAL PARTNERS" : "GSA CAPITAL PARTNERS L.L.P.",
    "HUTCHIN HILL CAPITAL" : "HUTCHIN HILL CAPITAL, LP",
    "INSIGHT INVESTMENT MANAGEMENT(GLOBAL)" : "INSIGHT INVESTMENT MANAGEMENT (GLOBAL) LIMITED", 
    "JPMORGAN ASSET MANAGEMENT (UK)": "JPMORGAN ASSET MANAGEMENT (UK) LIMITED",
    "LANSDOWNE PARTNERS (UK)": "LANSDOWNE PARTNERS (UK) LLP",
    "MAGNETAR FINANCIAL": "MAGNETAR FINANCIAL LLC",
    "MAGNOLIA ROAD CAPITAL PARTNERS": "MAGNOLIA ROAD CAPITAL PARTNERS LP",
    "MARSHALL WACE LLP" : "MARSHALL WACE LLP",
    "MELQART ASSET MANAGEMENT (UK)" : "MELQART ASSET MANAGEMENT (UK) LTD",
    "MILLENNIUM INTERNATIONAL": "MILLENNIUM INTERNATIONAL MANAGEMENT LP",
    "MYRIAD OPPORTUNITIES MASTER FUND" : "MYRIAD OPPORTUNITIES MASTER FUND LIMITED",
    "NUMERIC INVESTORS": "NUMERIC INVESTORS, LLC",
    "OCEANIC OPPORTUNITIES MASTER FUND": "OCEANIC OPPORTUNITIES MASTER FUND L.P.",
    "OCH-ZIFF MANAGEMENT EUROPE": "OCH-ZIFF MANAGEMENT EUROPE LIMITED",
    "OXFORD ASSET MANAGEMENT" : "OXFORD ASSET MANAGEMENT LLP",
    "PDT PARTNERS" : "PDT PARTNERS, LLC",
    "PINE RIVER CAPITAL MANAGEMENT" : "PINE RIVER CAPITAL MANAGEMENT L.P.",
    "PUBLIC EQUITY PARTNERS" : "PUBLIC EQUITY PARTNERS MANAGEMENT, L.P.",
    "QUANTITATIVE MANAGEMENT" : "QUANTITATIVE MANAGEMENT ASSOCIATES LLC",
    "QVT FINANCIAL" : "QVT FINANCIAL LP",
    "RAMIUS ADVISORS" : "RAMIUS ADVISORS, LLC",
    "RENAISSANCE TECHNOLOGIES" : "RENAISSANCE TECHNOLOGIES LLC",
    "ROBECO INVESTMENT MANAGEMENT" : "ROBECO INVESTMENT MANAGEMENT, INC.",
    "SUSQUEHANNA INTERNATIONAL GROUP" : "SUSQUEHANNA INTERNATIONAL GROUP LTD",
    "SUSQUEHANNA INTERNATIONALHOLDING" : "SUSQUEHANNA INTERNATIONAL HOLDINGS LLC",
    "SYLEBRA HK COMPANY" : "SYLEBRA HK COMPANY LIMITED",
    "UBS ASSET MANAGEMENT (UK)" : "UBS ASSET MANAGEMENT (UK) LTD",
    "UBS GLOBAL ASSET MANAGEMENT (UK)" : "UBS GLOBAL ASSET MANAGEMENT (UK) LTD",
    "UBS O'CONNOR LLC" : "UBS O'CONNOR LLC",
    "VIKING GLOBAL INVESTORS" : "VIKING GLOBAL INVESTORS LP",
    "VOLEON CAPITAL MANAGEMENT" : "VOLEON CAPITAL MANAGEMENT LP",
    "WELLINGTON MANAGEMENT COMPANY" : "WELLINGTON MANAGEMENT COMPANY", 
    "WHITEBOX ADVISORS LLC" : "WHITEBOX ADVISORS LLC"
        }



    for old, new in holders.items():
        cur.execute('''update {0} set HOLDER="{1}" where HOLDER like "%{2}%";'''.format(tbl, new, old))


    # set ISSUERs correct
    issuers = {
    "ACCOR"  : "ACCOR",
    "AIR FRANCE" : "AIR FRANCE-KLM",
    "ALSTOM" : "ALSTOM",
    "ARKEMA" : "ARKEMA",
    "ARTPRICE"  : "ARTPRICE.COM",
    "BOLLORE"  : "BOLLORE",
    "BOURBON" : "BOURBON",
    "BUREAU VERITAS"  : "BUREAU VERITAS",
    "CARREFOUR"  : "CARREFOUR",
    "CASINO GUICHARD-PERRACHON"  : "CASINO GUICHARD-PERRACHON",
    "CGG": "CGG",
    "MICHELIN" : "COMPAGNIE GENERALE DES ETABLISSEMENTS MICHELIN",
    "COMPAGNIE INDUSTRIELLE ET FIN": "COMPAGNIE INDUSTRIELLE ET FINANCIERE D’INGENIERIE INGENICO",
    "EDENRED": "EDENRED",
    "ELIS" : "ELIS",
    "ESSILOR" : "ESSILOR INTERNATIONAL",
    "EUTELSAT": "EUTELSAT COMMUNICATIONS",
    "FAURECIA" : "FAURECIA",
    "FNAC" : "GROUPE FNAC",
    "GAZTRANSPORT ET TECHNIGAZ" : "GAZTRANSPORT ET TECHNIGAZ",
    "GENFIT" : "GENFIT",
    "GROUPE EUROTUNNEL SE" : "GROUPE EUROTUNNEL SE",
    "GUERBET": "GUERBET",
    "ILIAD": "ILIAD",
    "INGENICO" : "INGENICO",
    "INNATE PHARMA" : "INNATE PHARMA",
    "JCDECAUX" : "JCDECAUX SA",
    "KORIAN" : "KORIAN",
    "L'OREAL" : "L'OREAL",
    "MERCIALYS" : "MERCIALYS",
    "NATUREX" : "NATUREX",
    "NEOPOST" : "NEOPOST S.A.",
    "NEXANS" : "NEXANS",
    "ORPEA" : "ORPEA",
    "PARROT" : "PARROT",
    "PEUGEOT" : "PEUGEOT S.A.",
    "PIERRE ET VACANCES" : "PIERRE ET VACANCES",
    "POXEL" : "POXEL",
    "RALLYE" : "RALLYE",
    "REMY COINTREAU" : "REMY COINTREAU",
    "SFR GROUP" : "SFR GROUP",
    "SOITEC" : "SOITEC",
    "SOLOCAL GROUP" : "SOLOCAL GROUP",
    "STMICROELECTRONICS" : "STMICROELECTRONICS NV",
    "TECHNICOLOR": "TECHNICOLOR",
    "TECHNIPFMC" : "TECHNIPFMC PLC",
    "TELEVISION FRANCAISE 1" : "TELEVISION FRANCAISE 1",
    "VALLOUREC" : "VALLOUREC",
    "VIVENDI" : "VIVENDI"
        }



    for old, new in issuers.items():
        cur.execute('''update {0} set ISSUER="{1}" where ISSUER like "%{2}%";'''.format(tbl, new, old))


    #closing connections
    con.commit()
    cur.close()
    con.close()


# run functions
Corrections('SourceData')
Corrections('RawSourceData')

print('\nDone\n')

